#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_docs.py — Generates README.md and burnbag.1 cleanly with UNIX line endings.
Bypasses web UI markdown parser bugs by avoiding nested code-fence literals.
"""

import os

# Programmatic code-fence delimiter to prevent UI markdown parser collisions
CB = chr(96) * 3

readme_lines = [
    "# burnbag",
    "",
    "**Ephemeral clamshell mode, power profile, and sleep inhibition for Linux laptops, featuring configurable safety timeouts.**",
    "",
    "`burnbag` is a desktop-agnostic, ephemeral D-Bus control utility for Fedora and Red Hat Enterprise Linux family systems running GNOME or standard systemd/freedesktop stacks. It allows a laptop (such as a ThinkPad T480) to continue operating with its lid closed—whether docked on a desk or thrown into a backpack—while managing performance profiles and enforcing optional safety countdowns.",
    "",
    "---",
    "",
    "## Why \"burnbag\"?",
    "",
    "In intelligence and government work, a burn bag is where classified documents go for destruction. In systems engineering, it is what your backpack turns into when you throw a running laptop compiling code inside with zero airflow. `burnbag` gives you explicit control over your thermals and sleep timers so you don't cook your hardware.",
    "",
    "---",
    "",
    "## Architecture & Safety Guarantees",
    "",
    "Unlike traditional lid-close scripts that permanently mutate `/etc/systemd/logind.conf` or set permanent `gsettings` overrides, `burnbag` uses **ephemeral D-Bus inhibitor file descriptors** (`org.freedesktop.login1.Manager.Inhibit`).",
    "",
    "* **Crash & Kill Immune:** Holding the returned Unix file descriptor open maintains the sleep/lid prohibition. If `burnbag` terminates normally, crashes, or is killed (`SIGINT`, `SIGTERM`, `SIGKILL`), the kernel closes the file descriptors, signaling `systemd-logind` to immediately drop the inhibitor locks and restore standard OS safety defaults.",
    "* **Power Profile Restoration:** `burnbag` queries `net.hadess.PowerProfiles` on startup to save your active power state. When the script exits or a lid cycle completes, it restores your original profile automatically.",
    "* **Narrative Verification:** Prints an explicit startup narrative before touching system state, and a structured teardown report upon exit detailing whether goals were achieved and any deviations observed.",
    "",
    "---",
    "",
    "## Requirements",
    "",
    "* **OS:** Fedora 44 / RHEL family distributions",
    "* **Python:** Distribution `/usr/bin/python3` (Python 3.9+)",
    "* **System Libraries:** `python3-gobject` (`PyGObject`)",
    "* **D-Bus Services:** `systemd-logind`, `power-profiles-daemon`, `UPower`",
    "",
    "Install or verify the RPM-provided Python binding from the checkout:",
    "",
    f"{CB}bash",
    "./scripts/install_prerequisites.sh",
    "./scripts/install_prerequisites.sh --check",
    CB,
    "",
    "The PyPI package named `gobject` is unrelated and does not provide the `gi` module used by burnbag.",
    "",
    "---",
    "",
    "## Installation",
    "",
    "Install prerequisites, the executable, and the manual page under `/usr/local`:",
    "",
    f"{CB}bash",
    "./install.sh",
    CB,
    "",
    "The installer requests `sudo` only when package or system-file installation requires it. Use `./install.sh --help` for staging and prefix options.",
    "",
    "For a repository-local development install, create live links under the ignored `.local/` tree:",
    "",
    f"{CB}bash",
    "./install.sh --mode dev",
    ".local/bin/burnbag --help",
    CB,
    "",
    "---",
    "",
    "## Modes & Syntax",
    "",
    f"{CB}text",
    "burnbag <MODE> [OPTIONS]",
    CB,
    "",
    "### Operational Modes",
    "",
    "| Mode | Description |",
    "|---|---|",
    "| `run` | Inhibit lid-close suspend; maintain currently active power profile. |",
    "| `run-cool` | Inhibit lid-close suspend; switch to `power-saver` profile. |",
    "| `run-balanced` | Inhibit lid-close suspend; switch to `balanced` profile. |",
    "| `run-hot` | Inhibit lid-close suspend; switch to `performance` profile. |",
    "| `suspend` | Immediately trigger a one-shot system suspend. |",
    "| `hibernate` | Immediately trigger a one-shot system hibernate (requires disk swap). |",
    "| `normal` | Clear active overrides and restore system defaults (`balanced` profile). |",
    "",
    "### Options",
    "",
    "* `--suspend-after-minutes <MIN>`: Unconditionally suspend after `MIN` minutes of continuous lid closure. If the lid is opened before the timer expires, the timer is cancelled.",
    "* `--no-inhibit-auto-suspend`: Allow standard OS background idle timers to suspend the system normally while lid-switch sleep remains blocked.",
    "* `--ignore-lid`: Keep a `run*` mode active when the lid opens. Lid opening still cancels an active suspend countdown; a later closure starts a fresh countdown. Without this option, the first observed close/open cycle ends the program.",
    "* `-h`, `--help`: Display syntax and usage help.",
    "",
    "---",
    "",
    "## Usage Examples",
    "",
    "**1. Run at maximum performance inside a bag with a 20-minute thermal/battery safety fuse:**",
    f"{CB}bash",
    "burnbag run-hot --suspend-after-minutes 20",
    CB,
    "",
    "**2. Run cool while listening to audiobooks or compiling background tasks with the lid closed:**",
    f"{CB}bash",
    "burnbag run-cool",
    CB,
    "",
    "**3. Keep running with lid closed, but allow standard GNOME background idle timeout to sleep the machine:**",
    f"{CB}bash",
    "burnbag run --no-inhibit-auto-suspend",
    CB,
    "",
    "**4. Immediately restore normal system power and sleep behavior:**",
    f"{CB}bash",
    "burnbag normal",
    CB,
    "",
    "**5. Stay active across repeated lid close/open cycles until interrupted or a timeout expires:**",
    f"{CB}bash",
    "burnbag run-cool --ignore-lid --suspend-after-minutes 20",
    CB,
]

man_lines = [
    '.\\" Man page for burnbag(1)',
    '.\\" Target platform: Fedora 44 / RHEL family',
    '.TH BURNBAG 1 "August 2026" "burnbag 1.0" "User Commands"',
    '.SH NAME',
    'burnbag \\- ephemeral clamshell mode, power profile, and sleep inhibition for Linux laptops',
    '.SH SYNOPSIS',
    '.B burnbag',
    '\\fIMODE\\fR [\\fIOPTIONS\\fR]',
    '.SH DESCRIPTION',
    '.B burnbag',
    'is a desktop\\-agnostic systems utility for Fedora and RHEL family Linux distributions that temporarily inhibits',
    '.B systemd-logind',
    'lid\\-switch and idle\\-suspend events, manages',
    '.B power\\-profiles\\-daemon',
    'performance profiles, and monitors hardware lid state via',
    '.BR UPower .',
    '.PP',
    'Unlike static configuration overrides,',
    '.B burnbag',
    'relies on ephemeral D\\-Bus inhibitor file descriptors. Holding these file descriptors open blocks the operating system from suspending when the laptop lid is shut. Upon normal exit, interrupt (\\fBSIGINT\\fR/\\fBSIGTERM\\fR), or process death (\\fBSIGKILL\\fR), the kernel releases the file descriptors, instructing',
    '.B systemd-logind',
    'to automatically drop all inhibitor locks and restore normal OS safety defaults.',
    '.PP',
    '.B burnbag',
    'provides narrative console logging on startup and exit, detailing intended system mutations, operational deviations, and the final shutdown state of D\\-Bus locks and power profiles.',
    '.SH MODES',
    'The following mutually exclusive operational modes are supported:',
    '.TP',
    '.B run',
    'Inhibit lid\\-close suspend events and maintain the currently active power profile. Persists until the lid is closed and subsequently reopened, a timeout expires, or an interrupt is received.',
    '.TP',
    '.B run\\-cool',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR power\\-saver .',
    'Runs as cool as possible to limit thermal buildup inside enclosed spaces.',
    '.TP',
    '.B run\\-balanced',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR balanced .',
    '.TP',
    '.B run\\-hot',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR performance .',
    '.TP',
    '.B suspend',
    'Immediately trigger a one\\-shot system suspend via D\\-Bus and exit.',
    '.TP',
    '.B hibernate',
    'Verify system hibernation capability via D\\-Bus and immediately hibernate. Fails early with an explicit error if disk swap is unavailable (e.g., standard Fedora',
    '.B zram',
    'configurations without dedicated swap storage).',
    '.TP',
    '.B normal',
    'Immediately restore system defaults: reset power profile to',
    '.BR balanced ,',
    'clear any active overrides, and exit.',
    '.SH OPTIONS',
    '.TP',
    '.BI \\-\\-suspend\\-after\\-minutes " MIN"',
    'Unconditionally suspend the system after',
    '.I MIN',
    'minutes of continuous lid closure. Designed as a safety fuse when running inside a backpack or bag. If the lid is reopened before',
    '.I MIN',
    'elapses, the countdown timer is cancelled.',
    '.TP',
    '.B \\-\\-no\\-inhibit\\-auto\\-suspend',
    'Do not acquire inhibitor locks for background system idle timers. The laptop will stay awake when the lid is closed, but standard OS idle policies (e.g., GNOME inactivity timeouts) remain permitted to trigger sleep.',
    '.TP',
    '.B \\-\\-ignore\\-lid',
    'Keep a run mode active when the lid opens instead of ending after the first observed close/open cycle. Opening the lid still cancels an active suspend countdown; a later closure starts a fresh countdown. Without this option, lid-open termination remains enabled by default.',
    '.TP',
    '.BR \\-h ", " \\-\\-help',
    'Display syntax, mode descriptions, and usage examples, then exit.',
    '.SH SAFETY & EPHEMERAL INHIBITION',
    'Modifying',
    '.I /etc/systemd/logind.conf',
    'or permanent',
    '.B gsettings',
    'keys to prevent lid\\-close suspend introduces a physical thermal hazard: if forgotten, a running laptop placed inside an unventilated bag may overheat.',
    '.PP',
    '.B burnbag',
    'mitigates this by utilizing D\\-Bus calls to',
    '.BR org.freedesktop.login1.Manager.Inhibit .',
    'The daemon returns a file descriptor handle for each lock. As long as',
    '.B burnbag',
    'holds the handle open, sleep is blocked. When',
    '.B burnbag',
    'terminates for any reason, the descriptor closes and default sleep safety policies immediately resume.',
    '.SH EXAMPLES',
    'Run in performance mode with a 15\\-minute thermal safety fuse:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-hot \\-\\-suspend\\-after\\-minutes 15',
    '.RE',
    '.PP',
    'Run in power\\-saver mode indefinitely until the lid is opened or Ctrl\\-C is pressed:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool',
    '.RE',
    '.PP',
    'Stay active across repeated lid cycles while retaining a 20\\-minute closed-lid safety fuse:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool \\-\\-ignore\\-lid \\-\\-suspend\\-after\\-minutes 20',
    '.RE',
    '.PP',
    'Restore normal system defaults immediately:',
    '.PP',
    '.RS 4',
    '.B burnbag normal',
    '.RE',
    '.SH EXIT STATUS',
    '.TP',
    '.B 0',
    'Successful execution, complete lid cycle observed, or clean termination via interrupt (\\fBSIGINT\\fR/\\fBSIGTERM\\fR).',
    '.TP',
    '.B 1',
    'Fatal error encountered (e.g., missing',
    '.B python3\\-gobject',
    'dependencies, D\\-Bus connection failure, or unsupported hibernation request).',
    '.SH INSTALLATION',
    'From a source checkout, install prerequisites, the executable, and this manual page with:',
    '.PP',
    '.B ./install.sh',
    '.PP',
    'For a repository\\-local development install under the ignored .local tree, use:',
    '.PP',
    '.B ./install.sh \\-\\-mode dev',
    '.SH SYSTEM REQUIREMENTS',
    'Requires the distribution /usr/bin/python3 (Python 3.9+),',
    '.BR python3\\-gobject ,',
    '.BR systemd\\-logind ,',
    '.BR power\\-profiles\\-daemon ,',
    'and',
    '.BR UPower .',
    '.SH AUTHOR',
    'Matthew C. Heck <mheck@hardproblemsgroup.com>',
    '.SH SEE ALSO',
    '.BR logind.conf (5),',
    '.BR systemd\\-logind.service (8),',
    '.BR upower (1),',
    '.BR powerprofilesctl (1)',
]

def main():
    with open("README.md", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(readme_lines) + "\n")

    with open("burnbag.1", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(man_lines) + "\n")

    os.chmod("README.md", 0o644)
    os.chmod("burnbag.1", 0o644)
    print("[INFO] Successfully generated README.md and burnbag.1 with clean UNIX line endings.")

if __name__ == "__main__":
    main()
