#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_docs.py — Generates README.md and burnbag.1 cleanly with UNIX line endings.
Bypasses web UI markdown parser bugs by avoiding nested code-fence literals.
"""

import os

# Programmatic code-fence delimiter to prevent UI markdown parser collisions
CB = chr(96) * 3

readme_lines = [
    "# burnbag",
    "",
    "**Ephemeral clamshell mode, backlight control, power profiles, and sleep inhibition for Linux laptops.**",
    "",
    "`burnbag` is a desktop-agnostic, ephemeral D-Bus control utility for Fedora and Red Hat Enterprise Linux family systems running GNOME or standard systemd/freedesktop stacks. It allows a laptop (such as a ThinkPad T480) to continue operating with its lid closed—whether docked on a desk or thrown into a backpack—while managing performance profiles and enforcing optional safety countdowns.",
    "",
    "---",
    "",
    "## Why \"burnbag\"?",
    "",
    "In intelligence and government work, a burn bag is where classified documents go for destruction. In systems engineering, it is what your backpack turns into when you throw a running laptop compiling code inside with zero airflow. `burnbag` gives you explicit control over your thermals and sleep timers so you don't cook your hardware.",
    "",
    "---",
    "",
    "## Architecture & Safety Guarantees",
    "",
    "Unlike traditional lid-close scripts that permanently mutate `/etc/systemd/logind.conf` or set permanent `gsettings` overrides, `burnbag` uses **ephemeral D-Bus inhibitor file descriptors** (`org.freedesktop.login1.Manager.Inhibit`).",
    "",
    "* **Crash & Kill Immune Inhibitors:** Holding the returned Unix file descriptor open maintains the sleep/lid prohibition. If `burnbag` terminates normally, crashes, or is killed (`SIGINT`, `SIGTERM`, `SIGKILL`), the kernel closes the file descriptors, signaling `systemd-logind` to immediately drop the inhibitor locks and restore standard OS sleep behavior.",
    "* **Default Backlight Control:** Persistent `run*` modes record every kernel screen-backlight device, turn the backlight off three seconds after process startup, verify it is off, and restore and verify a nonzero brightness before every handled exit. `--do-not-touch-backlight` explicitly opts out.",
    "* **Validated Display Session:** Backlight control prefers the process's active local logind session. Launchers outside direct PID accounting, including tmux and user-service scopes, fall back through an inherited session ID to the operator's primary graphical session. Every candidate must match the effective UID, be active, and be local.",
    "* **Explicit State Restoration:** On normal completion, handled `SIGINT`/`SIGTERM`, or a caught application error, `burnbag` restores the recorded backlight and power profile. `SIGKILL`, sudden power loss, and equivalent process destruction cannot run userspace teardown; unlike inhibitor FDs, explicit brightness and profile changes cannot be promised restoration in those cases.",
    "* **Narrative Verification:** Prints an explicit startup narrative before touching system state, and a structured teardown report upon exit detailing whether goals were achieved and any deviations observed.",
    "* **Adaptive Terminal Presentation:** Interactive terminals receive ANSI color and stronger visual hierarchy in runtime messages, help, usage tips, and errors. Redirected streams and explicit plain-output controls remain free of terminal escapes, and status meaning is always retained in text labels.",
    "* **Durable Running Log:** Every accepted operational session appends structured JSON Lines under the invoking user's XDG state directory. Each record is serialized across concurrent processes and synchronized with `fsync`; mutation intent is durable before safety-relevant host changes, and handled teardown is recorded before exit.",
    "",
    "---",
    "",
    "## Requirements",
    "",
    "* **OS:** Fedora 44 / RHEL family distributions",
    "* **Python:** Distribution `/usr/bin/python3` (Python 3.9+)",
    "* **System Libraries:** `python3-gobject` (`PyGObject`)",
    "* **D-Bus Services:** `systemd-logind`, `power-profiles-daemon`, `UPower`",
    "",
    "Install or verify the RPM-provided Python binding from the checkout:",
    "",
    f"{CB}bash",
    "./scripts/install_prerequisites.sh",
    "./scripts/install_prerequisites.sh --check",
    CB,
    "",
    "The PyPI package named `gobject` is unrelated and does not provide the `gi` module used by burnbag.",
    "",
    "---",
    "",
    "## Installation",
    "",
    "Install prerequisites, the executable, and the manual page under `/usr/local`:",
    "",
    f"{CB}bash",
    "./install.sh",
    CB,
    "",
    "The installer requests `sudo` only when package or system-file installation requires it. Use `./install.sh --help` for staging and prefix options.",
    "",
    "For a repository-local development install, run:",
    "",
    f"{CB}bash",
    "./install.sh --mode dev",
    "command -v burnbag",
    CB,
    "",
    "In an interactive terminal, dev mode reports any competing `burnbag` command and asks whether bare invocations should prefer this checkout. If accepted, it installs a managed launcher at `~/.local/bin/burnbag` and verifies that command lookup selects it. The user bin directory must already precede the installed command on `PATH`; the installer cannot change its parent shell's environment.",
    "",
    "Non-interactive dev installs leave command resolution unchanged unless policy is explicit:",
    "",
    f"{CB}bash",
    "./install.sh --mode dev --dev-command local",
    "BURNBAG_DEV_LAUNCHER_MODE=local ./install.sh --mode dev",
    CB,
    "",
    "Use `--dev-command system` to remove burnbag's managed user launcher and restore the other `PATH` result. Dev mode refuses to replace an unmanaged user launcher unless `--force` is explicit. When an automation environment supplies an isolated assistant `HOME`, pass `--user-home /absolute/operator/home`.",
    "",
    "---",
    "",
    "## Modes & Syntax",
    "",
    f"{CB}text",
    "burnbag <MODE> [OPTIONS]",
    CB,
    "",
    "### Operational Modes",
    "",
    "| Mode | Description |",
    "|---|---|",
    "| `run` | Inhibit lid-close suspend; maintain currently active power profile. |",
    "| `run-cool` | Inhibit lid-close suspend; switch to `power-saver` profile. |",
    "| `run-balanced` | Inhibit lid-close suspend; switch to `balanced` profile. |",
    "| `run-hot` | Inhibit lid-close suspend; switch to `performance` profile. |",
    "| `suspend` | Immediately trigger a one-shot system suspend. |",
    "| `hibernate` | Immediately trigger a one-shot system hibernate (requires disk swap). |",
    "| `normal` | Clear active overrides and restore system defaults (`balanced` profile). |",
    "",
    "### Options",
    "",
    "* `--suspend-after-minutes <MIN>`: Unconditionally suspend after `MIN` minutes of continuous lid closure. If the lid is opened before the timer expires, the timer is cancelled.",
    "* `--no-inhibit-auto-suspend`: Allow standard OS background idle timers to suspend the system normally while lid-switch sleep remains blocked.",
    "* `--ignore-lid`: Keep a `run*` mode active when the lid opens. Lid opening still cancels an active suspend countdown; a later closure starts a fresh countdown. Without this option, the first observed close/open cycle ends the program.",
    "* `--do-not-touch-backlight`: Leave the screen backlight untouched. Without this opt-out, persistent `run*` modes turn every discovered backlight off three seconds after process startup and restore and verify it as on before handled exit.",
    "* `--log-file <FILE>`: Write the mandatory synchronized running log to an explicit absolute path instead of the XDG state default. The parent must be owned by the effective user and must not be group/world writable.",
    "* `--no-color`: Disable ANSI color in runtime messages, help, usage, and error output. Color remains automatic by default for interactive terminals.",
    "* `-h`, `--help`: Display syntax and usage help.",
    "",
    "---",
    "",
    "## Terminal Output",
    "",
    "`burnbag` automatically adds color and visual hierarchy when the relevant standard-output or standard-error stream is an interactive terminal. It emits plain text when a stream is redirected, when `TERM=dumb`, when the `NO_COLOR` environment variable is present, or when `--no-color` is specified. Text labels such as `[INFO]`, `[OK]`, `[WARNING]`, and `[FATAL ERROR]` remain present in every mode, so color is never the only indication of status.",
    "",
    "Running `burnbag` without a mode prints a concise quick-start guide to standard error and exits with status 2. `burnbag --help`, the zero-argument guide, and command-line validation run before PyGObject is loaded, so they remain available even when runtime prerequisites are not yet installed.",
    "",
    "---",
    "",
    "## Durable Running Log",
    "",
    "Every accepted operational invocation must establish its running log before PyGObject is loaded or host state is changed. The default path is `$XDG_STATE_HOME/burnbag/burnbag.log`, or `$HOME/.local/state/burnbag/burnbag.log` when `XDG_STATE_HOME` is unset. `--log-file /absolute/path` selects another file; there is deliberately no no-log option.",
    "",
    "The log is UTF-8 JSON Lines. Records include UTC and monotonic time, a session UUID, sequence number, process and user IDs, selected mode, stable event code, severity, message, and structured details. `session_start` is synchronized before runtime initialization. A handled `session_end` is synchronized after backlight restoration, inhibitor release, and power-profile restoration. If a process or the machine dies before handled teardown, the missing `session_end` remains useful evidence instead of being fabricated later.",
    "",
    "Each complete record is appended while holding an exclusive advisory lock and is followed by `fsync` before the operation continues. The managed directory is mode `0700` and the log is mode `0600`; symlink targets, non-regular files, multiply linked files, wrong ownership, and unsafe parent permissions are rejected. Failure to open, append, lock, or synchronize the log prevents further host mutation and returns nonzero. If logging fails after state has changed, teardown still takes precedence and runs to completion.",
    "",
    "Burnbag does not rotate, upload, truncate, or delete this file. Retention is operator-owned. An external rename-based rotation leaves an already-running process on its open inode while later sessions use the configured path.",
    "",
    "Inspect recent records without changing them:",
    "",
    f"{CB}bash",
    "tail -n 20 \"${XDG_STATE_HOME:-$HOME/.local/state}/burnbag/burnbag.log\"",
    CB,
    "",
    "---",
    "",
    "## Usage Examples",
    "",
    "**1. Run at maximum performance inside a bag with a 20-minute thermal/battery safety fuse:**",
    f"{CB}bash",
    "burnbag run-hot --suspend-after-minutes 20",
    CB,
    "",
    "**2. Run cool while listening to audiobooks or compiling background tasks with the lid closed:**",
    f"{CB}bash",
    "burnbag run-cool",
    CB,
    "",
    "**3. Keep running with lid closed, but allow standard GNOME background idle timeout to sleep the machine:**",
    f"{CB}bash",
    "burnbag run --no-inhibit-auto-suspend",
    CB,
    "",
    "**4. Immediately restore normal system power and sleep behavior:**",
    f"{CB}bash",
    "burnbag normal",
    CB,
    "",
    "**5. Stay active across repeated lid close/open cycles until interrupted or a timeout expires:**",
    f"{CB}bash",
    "burnbag run-cool --ignore-lid --suspend-after-minutes 20",
    CB,
    "",
    "**6. Keep the screen backlight under desktop control instead of burnbag control:**",
    f"{CB}bash",
    "burnbag run-cool --do-not-touch-backlight",
    CB,
    "",
    "**7. Put an automation run in a separate synchronized log:**",
    f"{CB}bash",
    "burnbag run-cool --log-file /absolute/path/to/automation.jsonl",
    CB,
]

man_lines = [
    '.\\" Man page for burnbag(1)',
    '.\\" Target platform: Fedora 44 / RHEL family',
    '.TH BURNBAG 1 "August 2026" "burnbag 1.0" "User Commands"',
    '.SH NAME',
    'burnbag \\- ephemeral clamshell mode, power profile, and sleep inhibition for Linux laptops',
    '.SH SYNOPSIS',
    '.B burnbag',
    '\\fIMODE\\fR [\\fIOPTIONS\\fR]',
    '.SH DESCRIPTION',
    '.B burnbag',
    'is a desktop\\-agnostic systems utility for Fedora and RHEL family Linux distributions that temporarily inhibits',
    '.B systemd-logind',
    'lid\\-switch and idle\\-suspend events, controls screen backlights, manages',
    '.B power\\-profiles\\-daemon',
    'performance profiles, and monitors hardware lid state via',
    '.BR UPower .',
    '.PP',
    'Unlike static configuration overrides,',
    '.B burnbag',
    'relies on ephemeral D\\-Bus inhibitor file descriptors. Holding these file descriptors open blocks the operating system from suspending when the laptop lid is shut. Upon normal exit, interrupt (\\fBSIGINT\\fR/\\fBSIGTERM\\fR), or process death (\\fBSIGKILL\\fR), the kernel releases the file descriptors, instructing',
    '.B systemd-logind',
    'to automatically drop all inhibitor locks and restore normal OS safety defaults.',
    '.PP',
    'Persistent run modes use the caller\\(aqs',
    '.B org.freedesktop.login1.Session.SetBrightness',
    'interface to turn every discovered kernel screen backlight off three seconds after process startup. On every handled exit, burnbag restores the recorded brightness and verifies that the backlight reports a nonzero value before terminating.',
    '.PP',
    'The control session is resolved from the process session, inherited XDG_SESSION_ID, or the user\\(aqs primary graphical logind session. A candidate must belong to the effective UID, be active, and be local. This supports tmux and user-service launchers whose PIDs are not assigned directly to a logind session.',
    '.PP',
    'Explicit backlight and power\\-profile restoration can run after normal completion, handled SIGINT/SIGTERM, and caught application errors. It cannot run after SIGKILL, sudden power loss, or equivalent process destruction. Inhibitor file descriptors remain kernel\\-released in those cases.',
    '.PP',
    '.B burnbag',
    'provides narrative console logging on startup and exit, detailing intended system mutations, operational deviations, and the final shutdown state of D\\-Bus locks and power profiles.',
    '.PP',
    'Every accepted operational session also writes an append-only JSON Lines running log. Each complete record is serialized against concurrent burnbag writers and synchronized to the filesystem before execution continues.',
    '.SH MODES',
    'The following mutually exclusive operational modes are supported:',
    '.TP',
    '.B run',
    'Inhibit lid\\-close suspend events and maintain the currently active power profile. Persists until the lid is closed and subsequently reopened, a timeout expires, or an interrupt is received.',
    '.TP',
    '.B run\\-cool',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR power\\-saver .',
    'Runs as cool as possible to limit thermal buildup inside enclosed spaces.',
    '.TP',
    '.B run\\-balanced',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR balanced .',
    '.TP',
    '.B run\\-hot',
    'Inhibit lid\\-close suspend events and switch the system power profile to',
    '.BR performance .',
    '.TP',
    '.B suspend',
    'Immediately trigger a one\\-shot system suspend via D\\-Bus and exit.',
    '.TP',
    '.B hibernate',
    'Verify system hibernation capability via D\\-Bus and immediately hibernate. Fails early with an explicit error if disk swap is unavailable (e.g., standard Fedora',
    '.B zram',
    'configurations without dedicated swap storage).',
    '.TP',
    '.B normal',
    'Immediately restore system defaults: reset power profile to',
    '.BR balanced ,',
    'clear any active overrides, and exit.',
    '.SH OPTIONS',
    '.TP',
    '.BI \\-\\-suspend\\-after\\-minutes " MIN"',
    'Unconditionally suspend the system after',
    '.I MIN',
    'minutes of continuous lid closure. Designed as a safety fuse when running inside a backpack or bag. If the lid is reopened before',
    '.I MIN',
    'elapses, the countdown timer is cancelled.',
    '.TP',
    '.B \\-\\-no\\-inhibit\\-auto\\-suspend',
    'Do not acquire inhibitor locks for background system idle timers. The laptop will stay awake when the lid is closed, but standard OS idle policies (e.g., GNOME inactivity timeouts) remain permitted to trigger sleep.',
    '.TP',
    '.B \\-\\-ignore\\-lid',
    'Keep a run mode active when the lid opens instead of ending after the first observed close/open cycle. Opening the lid still cancels an active suspend countdown; a later closure starts a fresh countdown. Without this option, lid-open termination remains enabled by default.',
    '.TP',
    '.B \\-\\-do\\-not\\-touch\\-backlight',
    'Leave screen backlights untouched. Without this non-default opt-out, persistent run modes snapshot every kernel screen backlight, turn it off three seconds after process startup, verify it is off, and restore and verify a nonzero brightness before handled exit.',
    '.TP',
    '.BI \\-\\-log\\-file " FILE"',
    'Write the mandatory synchronized running log to absolute FILE instead of the XDG state default. The parent must be owned by the effective user and must not be group or world writable.',
    '.TP',
    '.B \\-\\-no\\-color',
    'Disable ANSI color in runtime messages, help, usage, and error output. Color remains automatic by default for interactive terminals.',
    '.TP',
    '.BR \\-h ", " \\-\\-help',
    'Display syntax, mode descriptions, and usage examples, then exit.',
    '.SH TERMINAL OUTPUT',
    'When the relevant standard-output or standard-error stream is an interactive terminal, burnbag automatically adds ANSI color and visual hierarchy. Output remains plain when a stream is redirected, when TERM=dumb, when the NO_COLOR environment variable is present, or when',
    '.B \\-\\-no\\-color',
    'is specified. Text labels such as [INFO], [OK], [WARNING], and [FATAL ERROR] remain present, so color is never the only status indication.',
    '.PP',
    'Invoking burnbag without a mode prints a concise quick-start guide to standard error and exits with status 2. Help, the zero-argument guide, and command-line validation run before PyGObject is loaded.',
    '.SH RUNNING LOG',
    'Every accepted operational invocation establishes a mandatory append-only running log before PyGObject is loaded or host state is changed. The default path is $XDG_STATE_HOME/burnbag/burnbag.log, falling back to $HOME/.local/state/burnbag/burnbag.log. There is no no-log option.',
    '.PP',
    'The UTF-8 JSON Lines records include UTC and monotonic time, a session UUID, sequence number, PID, effective UID, selected mode, stable event code, severity, message, and structured details. session_start is synchronized before runtime initialization. A handled session_end is synchronized after teardown. Absence of session_end is retained as evidence of an unhandled process or power interruption.',
    '.PP',
    'Each record is appended under an exclusive advisory lock and followed by fsync before execution continues. Safety-relevant mutation intent is synchronized before the mutation. Failure to resolve, open, validate, lock, append, or synchronize the log prevents further host mutation and returns nonzero. Logging failure never prevents backlight, inhibitor, or power-profile teardown.',
    '.PP',
    'The managed directory uses mode 0700 and the file mode 0600. Burnbag rejects symlink targets, non-regular or multiply linked files, incorrect ownership, and unsafe parent permissions. Burnbag does not rotate, upload, truncate, or delete logs; retention and external rename-based rotation are operator-owned.',
    '.SH SAFETY & EPHEMERAL INHIBITION',
    'Modifying',
    '.I /etc/systemd/logind.conf',
    'or permanent',
    '.B gsettings',
    'keys to prevent lid\\-close suspend introduces a physical thermal hazard: if forgotten, a running laptop placed inside an unventilated bag may overheat.',
    '.PP',
    '.B burnbag',
    'mitigates this by utilizing D\\-Bus calls to',
    '.BR org.freedesktop.login1.Manager.Inhibit .',
    'The daemon returns a file descriptor handle for each lock. As long as',
    '.B burnbag',
    'holds the handle open, sleep is blocked. When',
    '.B burnbag',
    'terminates for any reason, the descriptor closes and default sleep safety policies immediately resume.',
    '.SH EXAMPLES',
    'Run in performance mode with a 15\\-minute thermal safety fuse:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-hot \\-\\-suspend\\-after\\-minutes 15',
    '.RE',
    '.PP',
    'Run in power\\-saver mode indefinitely until the lid is opened or Ctrl\\-C is pressed:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool',
    '.RE',
    '.PP',
    'Stay active across repeated lid cycles while retaining a 20\\-minute closed-lid safety fuse:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool \\-\\-ignore\\-lid \\-\\-suspend\\-after\\-minutes 20',
    '.RE',
    '.PP',
    'Run in power\\-saver mode without changing the screen backlight:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool \\-\\-do\\-not\\-touch\\-backlight',
    '.RE',
    '.PP',
    'Run with an explicit synchronized log path:',
    '.PP',
    '.RS 4',
    '.B burnbag run\\-cool \\-\\-log\\-file /absolute/path/to/automation.jsonl',
    '.RE',
    '.PP',
    'Restore normal system defaults immediately:',
    '.PP',
    '.RS 4',
    '.B burnbag normal',
    '.RE',
    '.SH EXIT STATUS',
    '.TP',
    '.B 0',
    'Successful execution, complete lid cycle observed, or clean termination via interrupt (\\fBSIGINT\\fR/\\fBSIGTERM\\fR).',
    '.TP',
    '.B 1',
    'Fatal error or unverified required state encountered (e.g., missing',
    '.B python3\\-gobject',
    'dependencies, D\\-Bus connection failure, running-log durability failure, unsupported hibernation request, or backlight mutation/restoration failure).',
    '.TP',
    '.B 2',
    'Command-line usage error, including invocation without a required operational mode.',
    '.SH INSTALLATION',
    'From a source checkout, install prerequisites, the executable, and this manual page with:',
    '.PP',
    '.B ./install.sh',
    '.PP',
    'For a repository\\-local development install, use:',
    '.PP',
    '.B ./install.sh \\-\\-mode dev',
    '.PP',
    'Interactive dev mode reports a competing burnbag command and asks whether bare invocations should prefer the checkout. When accepted, it installs a managed launcher under $HOME/.local/bin and verifies effective command lookup. That directory must already precede the installed command on PATH because an installer cannot change its parent shell environment.',
    '.PP',
    'Non\\-interactive callers select checkout resolution explicitly with:',
    '.PP',
    '.B ./install.sh \\-\\-mode dev \\-\\-dev\\-command local',
    '.PP',
    'or set BURNBAG_DEV_LAUNCHER_MODE=local. Use \\-\\-dev\\-command system to remove the managed user launcher and retain the other PATH result. Use \\-\\-user\\-home with an explicit operator home when automation supplies an isolated assistant HOME.',
    '.SH SYSTEM REQUIREMENTS',
    'Requires the distribution /usr/bin/python3 (Python 3.9+),',
    '.BR python3\\-gobject ,',
    '.BR systemd\\-logind ,',
    '.BR power\\-profiles\\-daemon ,',
    'and',
    '.BR UPower .',
    '.SH AUTHOR',
    'Matthew C. Heck <mheck@hardproblemsgroup.com>',
    '.SH SEE ALSO',
    '.BR logind.conf (5),',
    '.BR systemd\\-logind.service (8),',
    '.BR upower (1),',
    '.BR powerprofilesctl (1)',
]

def main():
    with open("README.md", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(readme_lines) + "\n")

    with open("burnbag.1", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(man_lines) + "\n")

    os.chmod("README.md", 0o644)
    os.chmod("burnbag.1", 0o644)
    print("[INFO] Successfully generated README.md and burnbag.1 with clean UNIX line endings.")

if __name__ == "__main__":
    main()
